### ISSUE TITLE
Github API network timeout on every command

### ISSUE THREAD

**Issue by unparalleled-js** [vegaprotocol/vegawallet#489] opened 2022-02-22 02:18 UTC
Every command partially fails with a timeout to a Github API:

```
✗ couldn't check latest releases: couldn't get releases: couldn't deliver request: Get "https://api.github.com/repos/vegaprotocol/vegawallet/releases": dial tcp: lookup api.github.com on ***.***.**.*:**: read udp ***.***.**.*:**:*****->***.***.**.*:**: i/o timeout
```

I am using vegawallet version 0.12.0
version 2 wallet
macOS 12.2 Intel chip

**Comment by ValentinTrinque** [comment] 2022-02-22 09:30
I can't reproduce it. Can you tell me from where you installed the software (`brew`, `go install`, or `zip release`) ? 

Also, can you tell me what's the output of the following command?

```sh
curl https://api.github.com/repos/vegaprotocol/vegawallet/releases
```

**Comment by unparalleled-js** [comment] 2022-02-22 15:20
> I can't reproduce it. Can you tell me from where you installed the software (`brew`, `go install`, or `zip release`) ?

I downloaded the release from Github

> Also, can you tell me what's the output of the following command?

This is a very long list of JSON releases (looks like it is working?) I can paste the actual list if you need.

____

However, if I do something like `vegawallet service run --network fairground`, it _does_ start the service but the first output is the warning I posted in the issue.

**Comment by ValentinTrinque** [comment] 2022-03-04 18:26
That's pretty strange. If the `curl` command is working it means, nothing's stopping you to get this list.

**Comment by ValentinTrinque** [comment] 2022-03-04 18:27
We need to investigate this further.

**Comment by unparalleled-js** [comment] 2022-03-05 19:48
I am happy to help debug this further.

if there is anything you want me to try, let me know. I can set a breakpoint or we can do a call sometime this next week

**Comment by unparalleled-js** [comment] 2022-03-05 19:49
<img width="1687" alt="Screen Shot 2022-03-05 at 13 49 29" src="https://user-images.githubusercontent.com/19540978/156898054-77c7a846-678b-4ca1-b8b7-ee9a855de5d3.png">
 Here is a screenshot as further evidence

**Comment by ValentinTrinque** [comment] 2022-03-07 09:24
> I can set a breakpoint or we can do a call sometime this next week


That would be lovely. I will investigate on my side and discuss this with team. I will come back to you :)

**Comment by ValentinTrinque** [comment] 2022-03-15 16:20
@unparalleled-js just one last test, could you give us the output of:
```sh
time curl https://api.github.com/repos/vegaprotocol/vegawallet/releases > /dev/null
```

**Comment by ValentinTrinque** [comment] 2022-03-30 15:22
I haven't been able to reproduce it. Are you available on our Discord for some live debugging ?

**Comment by gordsport** [comment] 2022-08-02 10:01
Closing as not able to reproduce

**Closed by gordsport** 2022-08-02 10:01 UTC
Labels: wallet, Low, bug
